name: whereitis_2
description: "rebuild from wii"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_expandable_fab: ^2.0.0
  hive: ^2.2.3
  hive_flutter:
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  path: ^1.8.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
